
package com.hovs.rule14.sfi.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SFI", targetNamespace = "http://ws.sfi.rule14.hovs.com/", wsdlLocation = "http://localhost:8080/SFIws/services/soapapi/sfi?wsdl")
public class SFI
    extends Service
{

    private final static URL SFI_WSDL_LOCATION;
    private final static WebServiceException SFI_EXCEPTION;
    private final static QName SFI_QNAME = new QName("http://ws.sfi.rule14.hovs.com/", "SFI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SFIws/services/soapapi/sfi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SFI_WSDL_LOCATION = url;
        SFI_EXCEPTION = e;
    }

    public SFI() {
        super(__getWsdlLocation(), SFI_QNAME);
    }

    public SFI(WebServiceFeature... features) {
        super(__getWsdlLocation(), SFI_QNAME, features);
    }

    public SFI(URL wsdlLocation) {
        super(wsdlLocation, SFI_QNAME);
    }

    public SFI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SFI_QNAME, features);
    }

    public SFI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SFI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SFIService
     */
    @WebEndpoint(name = "SFIServicePort")
    public SFIService getSFIServicePort() {
        return super.getPort(new QName("http://ws.sfi.rule14.hovs.com/", "SFIServicePort"), SFIService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SFIService
     */
    @WebEndpoint(name = "SFIServicePort")
    public SFIService getSFIServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sfi.rule14.hovs.com/", "SFIServicePort"), SFIService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SFI_EXCEPTION!= null) {
            throw SFI_EXCEPTION;
        }
        return SFI_WSDL_LOCATION;
    }

}
