
package com.hovs.rule14.sfi.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SFIService", targetNamespace = "http://ws.sfi.rule14.hovs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SFIService {


    /**
     * 
     * @param sfiReportRequest
     * @return
     *     returns com.hovs.rule14.sfi.ws.SfiPrintReportResponse
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "printSfiReport", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.PrintSfiReport")
    @ResponseWrapper(localName = "printSfiReportResponse", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.PrintSfiReportResponse")
    public SfiPrintReportResponse printSfiReport(
        @WebParam(name = "SfiReportRequest", targetNamespace = "")
        SfiReportRequest sfiReportRequest)
        throws WsException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.hovs.rule14.sfi.ws.SaveUpdateUserResult
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "passwordChangeNxtTimeFlag", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.PasswordChangeNxtTimeFlag")
    @ResponseWrapper(localName = "passwordChangeNxtTimeFlagResponse", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.PasswordChangeNxtTimeFlagResponse")
    public SaveUpdateUserResult passwordChangeNxtTimeFlag(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws WsException_Exception
    ;

    /**
     * 
     * @param saveUpdateUserProfileRequest
     * @return
     *     returns com.hovs.rule14.sfi.ws.SaveUpdateUserResult
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveOrUpdateUserDetails", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.SaveOrUpdateUserDetails")
    @ResponseWrapper(localName = "saveOrUpdateUserDetailsResponse", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.SaveOrUpdateUserDetailsResponse")
    public SaveUpdateUserResult saveOrUpdateUserDetails(
        @WebParam(name = "SaveUpdateUserProfileRequest", targetNamespace = "")
        SaveUpdateUserProfileRequest saveUpdateUserProfileRequest)
        throws WsException_Exception
    ;

    /**
     * 
     * @param saveUpdateTaxPayerRequest
     * @return
     *     returns com.hovs.rule14.sfi.ws.SaveUpdateUserResult
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveOrUpdateUserProfile", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.SaveOrUpdateUserProfile")
    @ResponseWrapper(localName = "saveOrUpdateUserProfileResponse", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.SaveOrUpdateUserProfileResponse")
    public SaveUpdateUserResult saveOrUpdateUserProfile(
        @WebParam(name = "SaveUpdateTaxPayerRequest", targetNamespace = "")
        SaveUpdateUserProfileRequest saveUpdateTaxPayerRequest)
        throws WsException_Exception
    ;

    /**
     * 
     * @param getSfiW9FormRequest
     * @return
     *     returns com.hovs.rule14.sfi.ws.GetSfiW9FormResponse
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTINPayerData", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.GetTINPayerData")
    @ResponseWrapper(localName = "getTINPayerDataResponse", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.GetTINPayerDataResponse")
    public GetSfiW9FormResponse getTINPayerData(
        @WebParam(name = "GetSfiW9FormRequest", targetNamespace = "")
        GetSfiW9FormRequest getSfiW9FormRequest)
        throws WsException_Exception
    ;

    /**
     * 
     * @param w9FormRequest
     * @return
     *     returns com.hovs.rule14.sfi.ws.SaveOrUpdateResponse
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveOrUpdateW9FormDetails", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.SaveOrUpdateW9FormDetails")
    @ResponseWrapper(localName = "saveOrUpdateW9FormDetailsResponse", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.SaveOrUpdateW9FormDetailsResponse")
    public SaveOrUpdateResponse saveOrUpdateW9FormDetails(
        @WebParam(name = "W9FormRequest", targetNamespace = "")
        W9FormRequest w9FormRequest)
        throws WsException_Exception
    ;

    /**
     * 
     * @param w9FormGetRequest
     * @return
     *     returns com.hovs.rule14.sfi.ws.W9FormGetResponse
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getW9FormDetails", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.GetW9FormDetails")
    @ResponseWrapper(localName = "getW9FormDetailsResponse", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.GetW9FormDetailsResponse")
    public W9FormGetResponse getW9FormDetails(
        @WebParam(name = "W9FormGetRequest", targetNamespace = "")
        W9FormGetRequest w9FormGetRequest)
        throws WsException_Exception
    ;

    /**
     * 
     * @param getUserProfileRequest
     * @return
     *     returns com.hovs.rule14.sfi.ws.GetUserResponse
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserProfile", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.GetUserProfile")
    @ResponseWrapper(localName = "getUserProfileResponse", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.GetUserProfileResponse")
    public GetUserResponse getUserProfile(
        @WebParam(name = "GetUserProfileRequest", targetNamespace = "")
        GetUserProfileRequest getUserProfileRequest)
        throws WsException_Exception
    ;

    /**
     * 
     * @param getSfiW9FormRequest
     * @return
     *     returns com.hovs.rule14.sfi.ws.GetSfiW9PdfResponse
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getW9PdfData", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.GetW9PdfData")
    @ResponseWrapper(localName = "getW9PdfDataResponse", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.GetW9PdfDataResponse")
    public GetSfiW9PdfResponse getW9PdfData(
        @WebParam(name = "GetSfiW9FormRequest", targetNamespace = "")
        GetSfiW9FormRequest getSfiW9FormRequest)
        throws WsException_Exception
    ;

    /**
     * 
     * @param sfiReportRequest
     * @return
     *     returns com.hovs.rule14.sfi.ws.SfiReportResponse
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sfiReportDetails", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.SfiReportDetails")
    @ResponseWrapper(localName = "sfiReportDetailsResponse", targetNamespace = "http://ws.sfi.rule14.hovs.com/", className = "com.hovs.rule14.sfi.ws.SfiReportDetailsResponse")
    public SfiReportResponse sfiReportDetails(
        @WebParam(name = "SfiReportRequest", targetNamespace = "")
        SfiReportRequest sfiReportRequest)
        throws WsException_Exception
    ;

}
